[workspace]
resolver = "2"
members = [
    "crates/clarification-core",
    "crates/clarification-cli",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/source-matrix/Clarification"

[profile.release]
lto = true
codegen-units = 1
strip = true
opt-level = 3

[workspace.dependencies]
image = { version = "=0.24.7", default-features = false, features = ["png", "jpeg", "gif", "bmp", "webp", "ico", "pnm", "qoi"] }
